/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Components;

import Client.MainForm;
import Common.BaseItems.FilmsItemList;
import Common.BaseItems.PalimpsestItemList;
import XML.BaseXMLCommand;
import XML.Command;
import java.util.ArrayList;
import org.jdesktop.beansbinding.ELProperty;
import org.jdesktop.swingbinding.JListBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Daniele Ligorio
 */
public class ucPalinsest extends javax.swing.JPanel {

    /**
     * Creates new form ucPalinsest
     */
    MainForm _mainWindow;
    ArrayList<FilmsItemList> _filmItemList;
    ArrayList<PalimpsestItemList> _palimpsestItemList;
    JListBinding lb;
    int _currentSelectedFilmId = -1;
    public ucPalinsest(MainForm mainWindow) {
        _mainWindow = mainWindow;
        initComponents();
        LoadFilmList();
        InitPalinpsest();
    }
    public void LoadFilmList(){
        BaseXMLCommand<String, String, ArrayList<FilmsItemList>> command = new BaseXMLCommand<>("GetFilmList",  null, null);
        _mainWindow._runClient.sendQuery(Command.Encoder(command));
        BaseXMLCommand<String, String, ArrayList<FilmsItemList>> response = Command.Decoder(_mainWindow._runClient.getResponse());
        _filmItemList = (ArrayList<FilmsItemList>)response.getValue(); 
        
        lb = SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, _filmItemList, listFilms);
        ELProperty filmNameP = ELProperty.create("${title}");
        // add the detail binding
        lb.setDetailBinding(filmNameP);
        
        lb.bind();
    }
    public void InitPalinpsest(){
        c_Palinsest1.init(_mainWindow, "Lunedi", 2);
        c_Palinsest2.init(_mainWindow, "Martedì", 3);
        c_Palinsest3.init(_mainWindow, "Mercoledì", 4);
        c_Palinsest4.init(_mainWindow, "Giovedì", 5);
        c_Palinsest5.init(_mainWindow, "Venerdì", 6);
        c_Palinsest6.init(_mainWindow, "Sabato", 7);
        c_Palinsest7.init(_mainWindow, "Domenica", 1);
    }
    public void GetPalinsestByFilmId(int currentSelectedFilmId){
        BaseXMLCommand<String, String, String> command = new BaseXMLCommand<>("GetPalinsestByFilmId",  null, currentSelectedFilmId + "");
        _mainWindow._runClient.sendQuery(Command.Encoder(command));
        BaseXMLCommand<String, String, ArrayList<PalimpsestItemList>> response = Command.Decoder(_mainWindow._runClient.getResponse());
        _palimpsestItemList = (ArrayList<PalimpsestItemList>)response.getValue();
        SetPalinpsest();
    }
    public void SetPalinpsest(){
        c_Palinsest1.setPalimpsest(_currentSelectedFilmId, _palimpsestItemList);
        c_Palinsest2.setPalimpsest(_currentSelectedFilmId, _palimpsestItemList);
        c_Palinsest3.setPalimpsest(_currentSelectedFilmId, _palimpsestItemList);
        c_Palinsest4.setPalimpsest(_currentSelectedFilmId, _palimpsestItemList);
        c_Palinsest5.setPalimpsest(_currentSelectedFilmId, _palimpsestItemList);
        c_Palinsest6.setPalimpsest(_currentSelectedFilmId, _palimpsestItemList);
        c_Palinsest7.setPalimpsest(_currentSelectedFilmId, _palimpsestItemList);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c_Palinsest1 = new Controls.c_Palimpsest();
        c_Palinsest2 = new Controls.c_Palimpsest();
        c_Palinsest3 = new Controls.c_Palimpsest();
        c_Palinsest4 = new Controls.c_Palimpsest();
        c_Palinsest5 = new Controls.c_Palimpsest();
        c_Palinsest6 = new Controls.c_Palimpsest();
        c_Palinsest7 = new Controls.c_Palimpsest();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFilms = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(662, 307));

        listFilms.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listFilms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listFilmsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listFilms);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Film");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_Palinsest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_Palinsest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_Palinsest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_Palinsest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_Palinsest5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(c_Palinsest6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_Palinsest7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(c_Palinsest7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Palinsest6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Palinsest5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Palinsest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Palinsest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Palinsest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_Palinsest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listFilmsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listFilmsMouseClicked
        BaseXMLCommand<String, String, String> command = new BaseXMLCommand<>("GetFilmidByTitle",  null, listFilms.getSelectedValue().toString());
        _mainWindow._runClient.sendQuery(Command.Encoder(command));
        BaseXMLCommand<String, String, String> response = Command.Decoder(_mainWindow._runClient.getResponse());
        _currentSelectedFilmId = Integer.parseInt(response.getValue()); 
        GetPalinsestByFilmId(_currentSelectedFilmId);
    }//GEN-LAST:event_listFilmsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controls.c_Palimpsest c_Palinsest1;
    private Controls.c_Palimpsest c_Palinsest2;
    private Controls.c_Palimpsest c_Palinsest3;
    private Controls.c_Palimpsest c_Palinsest4;
    private Controls.c_Palimpsest c_Palinsest5;
    private Controls.c_Palimpsest c_Palinsest6;
    private Controls.c_Palimpsest c_Palinsest7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listFilms;
    // End of variables declaration//GEN-END:variables
}
