/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Controls;

import Client.MainForm;
import Common.ExportToPDF;

/**
 *
 * @author Gennaro Tortorelli
 */
public class c_BookingSummary extends javax.swing.JPanel {

    /**
     * Creates new form c_BookingSummary
     */
    MainForm _mainWindow;
    boolean canExport = false;
    public c_BookingSummary(MainForm mainWindow) {
        this._mainWindow = mainWindow;
        initComponents();
        ResetValue();
    }
    
    public void ResetValue(){
        lblDateValue.setText("");
        lblFilmValue.setText("");
        lblPriceValue.setText("");
        lblSeatedCountValue.setText("");
        lblSeatedListValue.setText("");
        lblTimeValue.setText("");
            
    }

    public void UpdateValue(boolean refreshSeated){
        String pickedDate = _mainWindow.tabBooking.datePicker.getPickedDate();
        Object timeValue = _mainWindow.tabBooking.timeItemList.getSelectedValue();
        Object filmValue = _mainWindow.tabBooking.filmsItemList.getSelectedValue();
        
        if(pickedDate != null)
            lblDateValue.setText(pickedDate);
        if(timeValue != null){
            String temp = "";
            switch(_mainWindow.tabBooking.timeItemList.getTimeIdAt(_mainWindow.tabBooking.timeItemList.getSelectedIndex())){
                case 0:
                    temp = "18-20";
                    break;
                case 1:
                    temp = "20-22";
                    break;
                case 2:
                    temp = "22-24";
                    break;
            }
            lblTimeValue.setText(temp);
        }
        if(filmValue != null){
            lblFilmValue.setText(_mainWindow.tabBooking.filmsItemList.getModel().getElementAt(_mainWindow.tabBooking.filmsItemList.getSelectedIndex()).toString());
        }
        if(refreshSeated == true){
            if(pickedDate != null && timeValue != null && filmValue != null && _mainWindow.tabBooking.seated.GetHallId() > 0)
            {
                _mainWindow.tabBooking.seated.LoadSeatedList();
                _mainWindow.tabBooking.seated.setVisible(true);
                Object countSeatedValue = _mainWindow.tabBooking.seated.CountSeated();
                Object listSeatedValueString = _mainWindow.tabBooking.seated.listSeatedValueString();
                if(countSeatedValue != null){
                    lblSeatedCountValue.setText(countSeatedValue.toString());
                }
                if(listSeatedValueString != null){
                    lblSeatedListValue.setText(listSeatedValueString.toString());
                }
                /*
                 * Calcolo del prezzo del biglietto
                 * 7: sabato, 1: Domenica. Prezzo => 7 euro
                 * Restanti giorni: 4 euro
                 */
                String dayWeek = _mainWindow.tabBooking.datePicker.getSelectedDay();
                if(dayWeek.equals("1") || dayWeek.equals("7"))
                    lblPriceValue.setText((Integer.parseInt(countSeatedValue.toString()) * 7) + " euro");
                else
                    lblPriceValue.setText((Integer.parseInt(countSeatedValue.toString()) * 4) + " euro");
                canExport = true;
            }
            else{
                _mainWindow.tabBooking.seated.setVisible(false);
                lblSeatedCountValue.setText("");
                lblSeatedListValue.setText("");
                lblPriceValue.setText("");
                canExport = false;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPrintTicket = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDateValue = new javax.swing.JLabel();
        lblTimeValue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFilmValue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSeatedCountValue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPriceValue = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSeatedListValue = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Riepilogo prenotazione");

        btnPrintTicket.setText("Stampa ricevuta");
        btnPrintTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintTicketActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Orario");

        lblDateValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDateValue.setText("29/01/2012");

        lblTimeValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTimeValue.setText("18-20");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Film");

        lblFilmValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFilmValue.setText("Il Gladiatore");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nr. Posti");

        lblSeatedCountValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSeatedCountValue.setText("2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Prezzo");

        lblPriceValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPriceValue.setText("10 Euro");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Posti");

        lblSeatedListValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSeatedListValue.setText("A1, B1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFilmValue, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPriceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeatedCountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeatedListValue, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPrintTicket))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDateValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTimeValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFilmValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSeatedListValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblPriceValue)
                    .addComponent(jLabel5)
                    .addComponent(lblSeatedCountValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintTicket)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintTicketActionPerformed
        if(canExport && _mainWindow.tabBooking.seated.CountSeated() > 0){
            ExportToPDF.CreatePDFFile(_mainWindow);
        }
    }//GEN-LAST:event_btnPrintTicketActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel lblDateValue;
    public javax.swing.JLabel lblFilmValue;
    public javax.swing.JLabel lblPriceValue;
    public javax.swing.JLabel lblSeatedCountValue;
    public javax.swing.JLabel lblSeatedListValue;
    public javax.swing.JLabel lblTimeValue;
    // End of variables declaration//GEN-END:variables
}
